insert into COUNTRY(name, version) values ('Afghanistan', 0)
insert into COUNTRY(name, version) values ('Albania', 0)
insert into COUNTRY(name, version) values ('Algeria', 0)
insert into COUNTRY(name, version) values ('American Samoa', 0)
insert into COUNTRY(name, version) values ('Andorra', 0)
insert into COUNTRY(name, version) values ('Angola', 0)
insert into COUNTRY(name, version) values ('Anguilla', 0)
insert into COUNTRY(name, version) values ('Antigua & Barbuda', 0)
insert into COUNTRY(name, version) values ('Argentina', 0)
insert into COUNTRY(name, version) values ('Armenia', 0)
insert into COUNTRY(name, version) values ('Aruba', 0)
insert into COUNTRY(name, version) values ('Australia', 0)
insert into COUNTRY(name, version) values ('Austria', 0)
insert into COUNTRY(name, version) values ('Azerbaijan', 0)
insert into COUNTRY(name, version) values ('Bahamas, The', 0)
insert into COUNTRY(name, version) values ('Bahrain', 0)
insert into COUNTRY(name, version) values ('Bangladesh', 0)
insert into COUNTRY(name, version) values ('Barbados', 0)
insert into COUNTRY(name, version) values ('Belarus', 0)
insert into COUNTRY(name, version) values ('Belgium', 0)
insert into COUNTRY(name, version) values ('Belize', 0)
insert into COUNTRY(name, version) values ('Benin', 0)
insert into COUNTRY(name, version) values ('Bermuda', 0)
insert into COUNTRY(name, version) values ('Bhutan', 0)
insert into COUNTRY(name, version) values ('Bolivia', 0)
insert into COUNTRY(name, version) values ('Bosnia & Herzegovina', 0)
insert into COUNTRY(name, version) values ('Botswana', 0)
insert into COUNTRY(name, version) values ('Brazil', 0)
insert into COUNTRY(name, version) values ('British Virgin Is.', 0)
insert into COUNTRY(name, version) values ('Brunei', 0)
insert into COUNTRY(name, version) values ('Bulgaria', 0)
insert into COUNTRY(name, version) values ('Burkina Faso', 0)
insert into COUNTRY(name, version) values ('Burma', 0)
insert into COUNTRY(name, version) values ('Burundi', 0)
insert into COUNTRY(name, version) values ('Cambodia', 0)
insert into COUNTRY(name, version) values ('Cameroon', 0)
insert into COUNTRY(name, version) values ('Canada', 0)
insert into COUNTRY(name, version) values ('Cape Verde', 0)
insert into COUNTRY(name, version) values ('Cayman Islands', 0)
insert into COUNTRY(name, version) values ('Central African Rep.', 0)
insert into COUNTRY(name, version) values ('Chad', 0)
insert into COUNTRY(name, version) values ('Chile', 0)
insert into COUNTRY(name, version) values ('China', 0)
insert into COUNTRY(name, version) values ('Colombia', 0)
insert into COUNTRY(name, version) values ('Comoros', 0)
insert into COUNTRY(name, version) values ('Congo, Dem. Rep.', 0)
insert into COUNTRY(name, version) values ('Congo, Repub. of the', 0)
insert into COUNTRY(name, version) values ('Cook Islands', 0)
insert into COUNTRY(name, version) values ('Costa Rica', 0)
insert into COUNTRY(name, version) values ('Cote d''Ivoire', 0)
insert into COUNTRY(name, version) values ('Croatia', 0)
insert into COUNTRY(name, version) values ('Cuba', 0)
insert into COUNTRY(name, version) values ('Cyprus', 0)
insert into COUNTRY(name, version) values ('Czech Republic', 0)
insert into COUNTRY(name, version) values ('Denmark', 0)
insert into COUNTRY(name, version) values ('Djibouti', 0)
insert into COUNTRY(name, version) values ('Dominica', 0)
insert into COUNTRY(name, version) values ('Dominican Republic', 0)
insert into COUNTRY(name, version) values ('East Timor', 0)
insert into COUNTRY(name, version) values ('Ecuador', 0)
insert into COUNTRY(name, version) values ('Egypt', 0)
insert into COUNTRY(name, version) values ('El Salvador', 0)
insert into COUNTRY(name, version) values ('Equatorial Guinea', 0)
insert into COUNTRY(name, version) values ('Eritrea', 0)
insert into COUNTRY(name, version) values ('Estonia', 0)
insert into COUNTRY(name, version) values ('Ethiopia', 0)
insert into COUNTRY(name, version) values ('Faroe Islands', 0)
insert into COUNTRY(name, version) values ('Fiji', 0)
insert into COUNTRY(name, version) values ('Finland', 0)
insert into COUNTRY(name, version) values ('France', 0)
insert into COUNTRY(name, version) values ('French Guiana', 0)
insert into COUNTRY(name, version) values ('French Polynesia', 0)
insert into COUNTRY(name, version) values ('Gabon', 0)
insert into COUNTRY(name, version) values ('Gambia, The', 0)
insert into COUNTRY(name, version) values ('Gaza Strip', 0)
insert into COUNTRY(name, version) values ('Georgia', 0)
insert into COUNTRY(name, version) values ('Germany', 0)
insert into COUNTRY(name, version) values ('Ghana', 0)
insert into COUNTRY(name, version) values ('Gibraltar', 0)
insert into COUNTRY(name, version) values ('Greece', 0)
insert into COUNTRY(name, version) values ('Greenland', 0)
insert into COUNTRY(name, version) values ('Grenada', 0)
insert into COUNTRY(name, version) values ('Guadeloupe', 0)
insert into COUNTRY(name, version) values ('Guam', 0)
insert into COUNTRY(name, version) values ('Guatemala', 0)
insert into COUNTRY(name, version) values ('Guernsey', 0)
insert into COUNTRY(name, version) values ('Guinea', 0)
insert into COUNTRY(name, version) values ('Guinea-Bissau', 0)
insert into COUNTRY(name, version) values ('Guyana', 0)
insert into COUNTRY(name, version) values ('Haiti', 0)
insert into COUNTRY(name, version) values ('Honduras', 0)
insert into COUNTRY(name, version) values ('Hong Kong', 0)
insert into COUNTRY(name, version) values ('Hungary', 0)
insert into COUNTRY(name, version) values ('Iceland', 0)
insert into COUNTRY(name, version) values ('India', 0)
insert into COUNTRY(name, version) values ('Indonesia', 0)
insert into COUNTRY(name, version) values ('Iran', 0)
insert into COUNTRY(name, version) values ('Iraq', 0)
insert into COUNTRY(name, version) values ('Ireland', 0)
insert into COUNTRY(name, version) values ('Isle of Man', 0)
insert into COUNTRY(name, version) values ('Israel', 0)
insert into COUNTRY(name, version) values ('Italy', 0)
insert into COUNTRY(name, version) values ('Jamaica', 0)
insert into COUNTRY(name, version) values ('Japan', 0)
insert into COUNTRY(name, version) values ('Jersey', 0)
insert into COUNTRY(name, version) values ('Jordan', 0)
insert into COUNTRY(name, version) values ('Kazakhstan', 0)
insert into COUNTRY(name, version) values ('Kenya', 0)
insert into COUNTRY(name, version) values ('Kiribati', 0)
insert into COUNTRY(name, version) values ('Korea, North', 0)
insert into COUNTRY(name, version) values ('Korea, South', 0)
insert into COUNTRY(name, version) values ('Kuwait', 0)
insert into COUNTRY(name, version) values ('Kyrgyzstan', 0)
insert into COUNTRY(name, version) values ('Laos', 0)
insert into COUNTRY(name, version) values ('Latvia', 0)
insert into COUNTRY(name, version) values ('Lebanon', 0)
insert into COUNTRY(name, version) values ('Lesotho', 0)
insert into COUNTRY(name, version) values ('Liberia', 0)
insert into COUNTRY(name, version) values ('Libya', 0)
insert into COUNTRY(name, version) values ('Liechtenstein', 0)
insert into COUNTRY(name, version) values ('Lithuania', 0)
insert into COUNTRY(name, version) values ('Luxembourg', 0)
insert into COUNTRY(name, version) values ('Macau', 0)
insert into COUNTRY(name, version) values ('Macedonia', 0)
insert into COUNTRY(name, version) values ('Madagascar', 0)
insert into COUNTRY(name, version) values ('Malawi', 0)
insert into COUNTRY(name, version) values ('Malaysia', 0)
insert into COUNTRY(name, version) values ('Maldives', 0)
insert into COUNTRY(name, version) values ('Mali', 0)
insert into COUNTRY(name, version) values ('Malta', 0)
insert into COUNTRY(name, version) values ('Marshall Islands', 0)
insert into COUNTRY(name, version) values ('Martinique', 0)
insert into COUNTRY(name, version) values ('Mauritania', 0)
insert into COUNTRY(name, version) values ('Mauritius', 0)
insert into COUNTRY(name, version) values ('Mayotte', 0)
insert into COUNTRY(name, version) values ('Mexico', 0)
insert into COUNTRY(name, version) values ('Micronesia, Fed. St.', 0)
insert into COUNTRY(name, version) values ('Moldova', 0)
insert into COUNTRY(name, version) values ('Monaco', 0)
insert into COUNTRY(name, version) values ('Mongolia', 0)
insert into COUNTRY(name, version) values ('Montserrat', 0)
insert into COUNTRY(name, version) values ('Morocco', 0)
insert into COUNTRY(name, version) values ('Mozambique', 0)
insert into COUNTRY(name, version) values ('Namibia', 0)
insert into COUNTRY(name, version) values ('Nauru', 0)
insert into COUNTRY(name, version) values ('Nepal', 0)
insert into COUNTRY(name, version) values ('Netherlands', 0)
insert into COUNTRY(name, version) values ('Netherlands Antilles', 0)
insert into COUNTRY(name, version) values ('New Caledonia', 0)
insert into COUNTRY(name, version) values ('New Zealand', 0)
insert into COUNTRY(name, version) values ('Nicaragua', 0)
insert into COUNTRY(name, version) values ('Niger', 0)
insert into COUNTRY(name, version) values ('Nigeria', 0)
insert into COUNTRY(name, version) values ('N. Mariana Islands', 0)
insert into COUNTRY(name, version) values ('Norway', 0)
insert into COUNTRY(name, version) values ('Oman', 0)
insert into COUNTRY(name, version) values ('Pakistan', 0)
insert into COUNTRY(name, version) values ('Palau', 0)
insert into COUNTRY(name, version) values ('Panama', 0)
insert into COUNTRY(name, version) values ('Papua New Guinea', 0)
insert into COUNTRY(name, version) values ('Paraguay', 0)
insert into COUNTRY(name, version) values ('Peru', 0)
insert into COUNTRY(name, version) values ('Philippines', 0)
insert into COUNTRY(name, version) values ('Poland', 0)
insert into COUNTRY(name, version) values ('Portugal', 0)
insert into COUNTRY(name, version) values ('Puerto Rico', 0)
insert into COUNTRY(name, version) values ('Qatar', 0)
insert into COUNTRY(name, version) values ('Reunion', 0)
insert into COUNTRY(name, version) values ('Romania', 0)
insert into COUNTRY(name, version) values ('Russia', 0)
insert into COUNTRY(name, version) values ('Rwanda', 0)
insert into COUNTRY(name, version) values ('Saint Helena', 0)
insert into COUNTRY(name, version) values ('Saint Kitts & Nevis', 0)
insert into COUNTRY(name, version) values ('Saint Lucia', 0)
insert into COUNTRY(name, version) values ('St Pierre & Miquelon', 0)
insert into COUNTRY(name, version) values ('Saint Vincent and the Grenadines', 0)
insert into COUNTRY(name, version) values ('Samoa', 0)
insert into COUNTRY(name, version) values ('San Marino', 0)
insert into COUNTRY(name, version) values ('Sao Tome & Principe', 0)
insert into COUNTRY(name, version) values ('Saudi Arabia', 0)
insert into COUNTRY(name, version) values ('Senegal', 0)
insert into COUNTRY(name, version) values ('Serbia', 0)
insert into COUNTRY(name, version) values ('Seychelles', 0)
insert into COUNTRY(name, version) values ('Sierra Leone', 0)
insert into COUNTRY(name, version) values ('Singapore', 0)
insert into COUNTRY(name, version) values ('Slovakia', 0)
insert into COUNTRY(name, version) values ('Slovenia', 0)
insert into COUNTRY(name, version) values ('Solomon Islands', 0)
insert into COUNTRY(name, version) values ('Somalia', 0)
insert into COUNTRY(name, version) values ('South Africa', 0)
insert into COUNTRY(name, version) values ('Spain', 0)
insert into COUNTRY(name, version) values ('Sri Lanka', 0)
insert into COUNTRY(name, version) values ('Sudan', 0)
insert into COUNTRY(name, version) values ('Suriname', 0)
insert into COUNTRY(name, version) values ('Swaziland', 0)
insert into COUNTRY(name, version) values ('Sweden', 0)
insert into COUNTRY(name, version) values ('Switzerland', 0)
insert into COUNTRY(name, version) values ('Syria', 0)
insert into COUNTRY(name, version) values ('Taiwan', 0)
insert into COUNTRY(name, version) values ('Tajikistan', 0)
insert into COUNTRY(name, version) values ('Tanzania', 0)
insert into COUNTRY(name, version) values ('Thailand', 0)
insert into COUNTRY(name, version) values ('Togo', 0)
insert into COUNTRY(name, version) values ('Tonga', 0)
insert into COUNTRY(name, version) values ('Trinidad & Tobago', 0)
insert into COUNTRY(name, version) values ('Tunisia', 0)
insert into COUNTRY(name, version) values ('Turkey', 0)
insert into COUNTRY(name, version) values ('Turkmenistan', 0)
insert into COUNTRY(name, version) values ('Turks & Caicos Is', 0)
insert into COUNTRY(name, version) values ('Tuvalu', 0)
insert into COUNTRY(name, version) values ('Uganda', 0)
insert into COUNTRY(name, version) values ('Ukraine', 0)
insert into COUNTRY(name, version) values ('United Arab Emirates', 0)
insert into COUNTRY(name, version) values ('United Kingdom', 0)
insert into COUNTRY(name, version) values ('United States', 0)
insert into COUNTRY(name, version) values ('Uruguay', 0)
insert into COUNTRY(name, version) values ('Uzbekistan', 0)
insert into COUNTRY(name, version) values ('Vanuatu', 0)
insert into COUNTRY(name, version) values ('Venezuela', 0)
insert into COUNTRY(name, version) values ('Vietnam', 0)
insert into COUNTRY(name, version) values ('Virgin Islands', 0)
insert into COUNTRY(name, version) values ('Wallis and Futuna', 0)
insert into COUNTRY(name, version) values ('West Bank', 0)
insert into COUNTRY(name, version) values ('Western Sahara', 0)
insert into COUNTRY(name, version) values ('Yemen', 0)
insert into COUNTRY(name, version) values ('Zambia', 0)
insert into COUNTRY(name, version) values ('Zimbabwe', 0)
