
package com.ecocoma.service.shipping.ups;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Cocoma UPS Shipping Web Services.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UPS_Service", targetNamespace = "http://service.ecocoma.com/shipping/ups", wsdlLocation = "http://service.ecocoma.com/shipping/ups.asmx?WSDL")
public class UPSService
    extends Service
{
    private final static URL UPSSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPSSERVICE_EXCEPTION;
    private final static QName UPSSERVICE_QNAME = new QName("http://service.ecocoma.com/shipping/ups", "UPS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://service.ecocoma.com/shipping/ups.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPSSERVICE_WSDL_LOCATION = url;
        UPSSERVICE_EXCEPTION = e;
    }

    public UPSService() {
        super(__getWsdlLocation(), UPSSERVICE_QNAME);
    }

    public UPSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPSSERVICE_QNAME, features);
    }

    public UPSService(URL wsdlLocation) {
        super(wsdlLocation, UPSSERVICE_QNAME);
    }

    public UPSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPSSERVICE_QNAME, features);
    }

    public UPSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UPSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UPSServiceSoap
     */
    @WebEndpoint(name = "UPS_ServiceSoap")
    public UPSServiceSoap getUPSServiceSoap() {
        return super.getPort(new QName("http://service.ecocoma.com/shipping/ups", "UPS_ServiceSoap"), UPSServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UPSServiceSoap
     */
    @WebEndpoint(name = "UPS_ServiceSoap")
    public UPSServiceSoap getUPSServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ecocoma.com/shipping/ups", "UPS_ServiceSoap"), UPSServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPSSERVICE_EXCEPTION!= null) {
            throw UPSSERVICE_EXCEPTION;
        }
        return UPSSERVICE_WSDL_LOCATION;
    }

}
