
package com.ecocoma.service.shipping.ups;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UPS_ServiceSoap", targetNamespace = "http://service.ecocoma.com/shipping/ups")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UPSServiceSoap {


    /**
     * Get UPS shipping rate.
     * 
     * @param weight
     * @param domainID
     * @param value
     * @param keyID
     * @param origCountry
     * @param destCountry
     * @param destPostal
     * @param origPostal
     * @return
     *     returns com.ecocoma.service.shipping.ups.Shipping
     */
    @WebMethod(operationName = "GetUPSRate", action = "http://service.ecocoma.com/shipping/ups/GetUPSRate")
    @WebResult(name = "GetUPSRateResult", targetNamespace = "http://service.ecocoma.com/shipping/ups")
    @RequestWrapper(localName = "GetUPSRate", targetNamespace = "http://service.ecocoma.com/shipping/ups", className = "com.ecocoma.service.shipping.ups.GetUPSRate")
    @ResponseWrapper(localName = "GetUPSRateResponse", targetNamespace = "http://service.ecocoma.com/shipping/ups", className = "com.ecocoma.service.shipping.ups.GetUPSRateResponse")
    public Shipping getUPSRate(
        @WebParam(name = "KeyID", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String keyID,
        @WebParam(name = "DomainID", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String domainID,
        @WebParam(name = "origPostal", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String origPostal,
        @WebParam(name = "origCountry", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String origCountry,
        @WebParam(name = "destPostal", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String destPostal,
        @WebParam(name = "destCountry", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String destCountry,
        @WebParam(name = "Weight", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String weight,
        @WebParam(name = "Value", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String value);

    /**
     * Get extended UPS shipping rate.
     * 
     * @param weight
     * @param domainID
     * @param value
     * @param keyID
     * @param origCountry
     * @param options
     * @param destCountry
     * @param destPostal
     * @param origPostal
     * @return
     *     returns com.ecocoma.service.shipping.ups.Shipping
     */
    @WebMethod(operationName = "GetExtendedUPSRate", action = "http://service.ecocoma.com/shipping/ups/GetExtendedUPSRate")
    @WebResult(name = "GetExtendedUPSRateResult", targetNamespace = "http://service.ecocoma.com/shipping/ups")
    @RequestWrapper(localName = "GetExtendedUPSRate", targetNamespace = "http://service.ecocoma.com/shipping/ups", className = "com.ecocoma.service.shipping.ups.GetExtendedUPSRate")
    @ResponseWrapper(localName = "GetExtendedUPSRateResponse", targetNamespace = "http://service.ecocoma.com/shipping/ups", className = "com.ecocoma.service.shipping.ups.GetExtendedUPSRateResponse")
    public Shipping getExtendedUPSRate(
        @WebParam(name = "KeyID", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String keyID,
        @WebParam(name = "DomainID", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String domainID,
        @WebParam(name = "origPostal", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String origPostal,
        @WebParam(name = "origCountry", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String origCountry,
        @WebParam(name = "destPostal", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String destPostal,
        @WebParam(name = "destCountry", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String destCountry,
        @WebParam(name = "Weight", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String weight,
        @WebParam(name = "Value", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        String value,
        @WebParam(name = "Options", targetNamespace = "http://service.ecocoma.com/shipping/ups")
        Options options);

}
