// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package si.kcclass.deliverycost.domain;

import org.springframework.beans.factory.annotation.Configurable;
import si.kcclass.deliverycost.domain.PostDataOnDemand;

privileged aspect PostDataOnDemand_Roo_Configurable {
    
    declare @type: PostDataOnDemand: @Configurable;
    
}
