// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package si.kcclass.deliverycost.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import si.kcclass.deliverycost.domain.Post;
import si.kcclass.deliverycost.domain.PostDataOnDemand;

privileged aspect PostDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PostDataOnDemand: @Component;
    
    private Random PostDataOnDemand.rnd = new SecureRandom();
    
    private List<Post> PostDataOnDemand.data;
    
    public Post PostDataOnDemand.getNewTransientPost(int index) {
        Post obj = new Post();
        setName(obj, index);
        setZipCode(obj, index);
        return obj;
    }
    
    public void PostDataOnDemand.setName(Post obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void PostDataOnDemand.setZipCode(Post obj, int index) {
        String zipCode = "zipCode_" + index;
        obj.setZipCode(zipCode);
    }
    
    public Post PostDataOnDemand.getSpecificPost(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Post obj = data.get(index);
        Long id = obj.getId();
        return Post.findPost(id);
    }
    
    public Post PostDataOnDemand.getRandomPost() {
        init();
        Post obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Post.findPost(id);
    }
    
    public boolean PostDataOnDemand.modifyPost(Post obj) {
        return false;
    }
    
    public void PostDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Post.findPostEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Post' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Post>();
        for (int i = 0; i < 10; i++) {
            Post obj = getNewTransientPost(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
